### ISSUE TITLE
Can't generate audiosprite

### ISSUE THREAD

**Issue by svebeck** [tonistiigi/audiosprite#13]
I tried to create an audiosprite for my game. But audiosprite always fail with the same error.

stefans-mbp:sounds stefansvebeck$ sudo audiosprite --log debug *.mp3
debug: Parsed arguments _=[bk_between_questions.mp3, bk_dialog_1.mp3, bk_dialog_2.mp3, bk_final_round.mp3, bk_main_1.mp3, bk_main_2.mp3, bk_question.mp3, ch_ming.mp3, ch_nemi.mp3, ch_rosanna.mp3, ch_simon.mp3, fx_after_question.mp3, fx_before_question.mp3, fx_bladlusen.mp3, fx_bladlusen_short.mp3, fx_click.mp3, fx_liv.mp3, fx_liv_short.mp3, fx_pr.mp3, fx_right.mp3, fx_right_short.mp3, fx_round_new.mp3, fx_wrong.mp3, fx_wrong_scary.mp3], log=debug, l=debug, output=output, o=output, path=, u=, export=ogg,m4a,mp3,ac3, e=ogg,m4a,mp3,ac3, format=default, f=default, autoplay=null, a=null, silence=0, s=0, gap=1, g=1, minlength=0, m=0, samplerate=44100, r=44100, channels=1, c=1, rawparts=, p=, $0=node /usr/local/bin/audiosprite
debug: Created temporary file file=/tmp/audiosprite.24839226342737675
debug: Spawn cmd=ffmpeg -version

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

**Comment by SargoDarya** [comment]
Pretty sure that is already there in the README.
