### ISSUE TITLE
*.mp3 doens't find all mp3-files

### ISSUE THREAD

**Issue by kluplau** [tonistiigi/audiosprite#18]
Hi,
When I try to add all the mp3-files in the directory, i get this:

![No errors](https://cloud.githubusercontent.com/assets/1536598/3433996/39120ef4-0085-11e4-9539-dc1dcfa52284.png)

Only if I specify each file, it works.

Do you have an idea what to do?

**Comment by zlumer** [comment]
Fixed in #41 (v.0.6.0 on npm)
