### ISSUE TITLE
Beep end time not 1.77

### ISSUE THREAD

**Issue by blvz** [tonistiigi/audiosprite#33]
```sh
$ git clone git@github.com:tonistiigi/audiosprite.git
$ cd audiosprite
$ npm install
$ npm test

...
Uncaught AssertionError: beep end time not 1.77
```

Am I missing something?

**Edit**: Oh, it's `1.7235147392290249` btw.

**Comment by tonistiigi** [comment]
Probably not. Just need to make allowed error `0.05` instead of `0.04` in https://github.com/tonistiigi/audiosprite/blob/master/test/test.js#L87 . Because mp3 is lossy it also doesn't preserve the file length precisely.

**Comment by blvz** [comment]
Very interesting, indeed. Thanks for the quick reply.
