### ISSUE TITLE
*.wav pattern for files doesn't work 

### ISSUE THREAD

**Issue by SeminYun** [tonistiigi/audiosprite#38]
'audiosprite --o test *.wav'  doesn't work.

'audiosprite --o test a.wav b.wav'  worked...

os window7
installed by npm

![32](https://cloud.githubusercontent.com/assets/5058355/11991510/a6dca762-aa5e-11e5-91b6-5dfd24370fc4.png)

**Comment by zlumer** [comment]
Fixed in #41 (v.0.6.0 on NPM)
