### ISSUE TITLE
API Usage

### ISSUE THREAD

**Issue by JacoBotha** [tonistiigi/audiosprite#46]
Hi

I am busy writing a little app that uses a UI to create AudioSprites.  Im running into an issue where when my app is packaged it does not seem to find ffmpeg.  Is there a way to bundle ffmpeg into my app and point audiosprite to that file?  Also, where do the exported files get created when using the API?

Not sure if this is an issue or just lack of documentation or maybe my own stupidity.

Regards

PS: This is the error im getting :

Uncaught Exception:
Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)

**Comment by SargoDarya** [comment]
That happens when you haven't installed ffmpeg.

**Comment by LuisAlejandro** [comment]
Hi! I'm having this same issue and I'm pretty sure I have ffmpeg installed.

If I execute audiosprite from the commanline like this:

node_modules/.bin/audiosprite

It works. But if I use it inside a script, it doesn't. what could be happening?

Thanks.
