### ISSUE TITLE
howler.js v2 uses property src instead urls 

### ISSUE THREAD

**Issue by k2s** [tonistiigi/audiosprite#48]
https://github.com/goldfire/howler.js/blob/master/howler.js#L237 vs.  https://github.com/goldfire/howler.js/blob/2.0/src/howler.core.js#L424

**Comment by roschler** [comment]
I see that this issue has been addressed.  But the version that gets pulled down with "npm i audiosprite -g" still generates JSON with the `urls` property and not the `src` property, which is what led me here.  Does the npm version have the fix?  I'll just hand edit the node module code for now, but I thought I'd let you know.

I'm using Howler JS 2.1.2.
