### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by endel** [tonistiigi/audiosprite#51]
For some reason, after installing the package, the binary `audiosprite` has wrong line endings, resulting this error.

```
$ npm install --save-dev audiosprite
$ ./node_modules/.bin/audiosprite --help
env: node\r: No such file or directory
```

I've cloned the project locally and `./cli.js` works properly - no problem with line ending. Maybe publishing to NPM from a windows machine mess up with line endings? 

More info about this here: https://github.com/npm/npm/issues/4607

**Comment by michaelcontento** [comment]
Same issue here. A simple workaround is to skip the shebang line via:

```bash
$ node ./node_modules/.bin/audiosprite --help
```

**Comment by metalim** [comment]
ping!
0.6.0 is broken on npm. Will you fix it?

**Comment by devon** [comment]
Solution 1:

```
npm uninstall audiosprite
npm install -g audiosprite@0.5.0
```

Solution 2:

get node_module path:

```
npm config get prefix
```

modify \r\n in cli.js (on mac)

```
cd the_path # the path find in npm config get prefix
brew install dos2unix
dos2unix lib/node_modules/audiosprite/cli.js
```

**Comment by endel** [comment]
Just created a pull request here: https://github.com/tonistiigi/audiosprite/pull/54

**Comment by BenBergman** [comment]
I fixed this issue on my machine by opening up `/usr/local/bin/audiosprite` in vim, running `:set ff=unix`, and saved the file. That converted the DOS line endings to Unix ones.

**Comment by SargoDarya** [comment]
This should be fixed through #54 and through commit a60c7640c1a0c92d3ecb6e6d1125479b098d9474 . Install the latest dev channel or wait for the next tagged release.

**Comment by psabharwal123** [comment]
when is 0.7.0 going to be published to npm?

**Comment by SargoDarya** [comment]
I've sent @tonistiigi a mail asking for NPM access. I'll push out the latest version when I have that.

**Comment by SargoDarya** [comment]
The latest version has been pushed to npm and is available as of right now.
