### ISSUE TITLE
--gap options does not work

### ISSUE THREAD

**Issue by salos1982** [tonistiigi/audiosprite#52]
I need no gap between sound sprites but logs shows that gaps are added and quite big gaps
e.g.
cmd line: audiosprite -l debug --output d:/work/hero/sounds-reduced -f howler -v 3 -g 0.0001 D:/work/hero/src/branches/small/res/sounds-reduced/*
output
info: File added OK file=C:\Users\SSOLOZ~1\AppData\Local\Temp\audiosprite.6968405144289136, duration=1.629750566893424
info: Silence gap added duration=0.370349433106576
debug: Start processing file=D:/work/hero/src/branches/small/res/sounds-reduced/stone_fall.ogg
debug: Spawn cmd=ffmpeg -i D:\work\hero\src\branches\small\res\sounds-reduced\stone_fall.ogg -ar 44100 -ac 1 -f s16le pipe:
info: File added OK file=C:\Users\SSOLOZ~1\AppData\Local\Temp\audiosprite.26521250791847706, duration=0.21623582766439908
info: Silence gap added duration=0.7838641723356009
debug: Start processing file=D:/work/hero/src/branches/small/res/sounds-reduced/stones_collision.ogg
debug: Spawn cmd=ffmpeg -i D:\work\hero\src\branches\small\res\sounds-reduced\stones_collision.ogg -ar 44100 -ac 1 -f s16le pipe:
info: File added OK file=C:\Users\SSOLOZ~1\AppData\Local\Temp\audiosprite.707215964095667, duration=0.14512471655328799
info: Silence gap added duration=0.854975283446712
debug: Start processing file=D:/work/hero/src/branches/small/res/sounds-reduced/stones_collision2.ogg
debug: Spawn cmd=ffmpeg -i D:\work\hero\src\branches\small\res\sounds-reduced\stones_collision2.ogg -ar 44100 -ac 1 -f s16le pipe:
info: File added OK file=C:\Users\SSOLOZ~1\AppData\Local\Temp\audiosprite.14779552235268056, duration=0.2620181405895692
info: Silence gap added duration=0.7380818594104308
debug: Start processing file=D:/work/hero/src/branches/small/res/sounds-reduced/stopwatch_add.ogg
debug: Spawn cmd=ffmpeg -i D:\work\hero\src\branches\small\res\sounds-reduced\stopwatch_add.ogg -ar 44100 -ac 1 -f s16le pipe:

**Comment by SargoDarya** [comment]
I'm pretty sure that was done so the audio files always start at a round second. I'm not sure though if that should be honoured if there's the gap option present.

**Comment by salos1982** [comment]
yes it always start at round second. It increases output file a lot (30% in my case).
