### ISSUE TITLE
File export (ffmpeg) is hanging because spawned ffmpeg output is not processed

### ISSUE THREAD

**Issue by rgal75** [tonistiigi/audiosprite#57]
Having given `audiosprite` many input mp3's, we have found that final file export never completes.

It seems, the reason is that `ffmpeg`'s output buffer gets full and should be read out. Otherwise it starts hanging. (Please, check the following: http://stackoverflow.com/questions/20792427/why-is-my-node-child-process-that-i-created-via-spawn-hanging)

As a workaround, we tried to specify the `-v quiet` option to `ffmpeg` and it solved the problem. Also specifying `{stdio: 'ignore'}` to spawn solves the issue.

**Comment by SargoDarya** [comment]
Could you provide a pull request for this?

**Comment by SargoDarya** [comment]
This might have been fixed through #73 . I'd kindly ask you to reevaluate with the v0.7.1 release and reopen this if it's reproducable.
