### ISSUE TITLE
It publish some empty audio file, zero length

### ISSUE THREAD

**Issue by yangfanyu** [tonistiigi/audiosprite#59]
"spritemap": {
    "a_lose": {
      "start": 0,
      "end": 0,
      "loop": false
    },
    "a_sitdown": {
      "start": 1,
      "end": 1,
      "loop": false
    },
    "a_standup": {
      "start": 2,
      "end": 2,
      "loop": false
    },
...........................
File added OK file=/var/folders/kk/nc3_3h215n928hptm6g52ps40000gn/T/audiosprite.7941562433261424, duration=0

**Comment by SargoDarya** [comment]
Could you provide the command line invocation for this and the directory structure?

**Comment by SargoDarya** [comment]
I'm closing this as it's missing valuable information. Feel free to reopen this when there is more information available.
