### ISSUE TITLE
Ubuntu 16.04 compatability

### ISSUE THREAD

**Issue by AgeOfLearning** [tonistiigi/audiosprite#60]
To make this work on Ubuntu I had to symlink avconv as ffmpeg and change line 166 to add "-strict -2" just before the output file name

    spawn('ffmpeg',['-y', '-ar', opts.samplerate, '-ac', opts.channels, '-f', 's16le', '-i', src]
        .concat(opt).concat(['-strict','-2']).concat(outfile))

**Comment by SargoDarya** [comment]
This should be fixed through #36 and will land in the next tagged version. Until the you could install the latest develop branch.
