### ISSUE TITLE
README ffmpeg brew install command

### ISSUE THREAD

**Issue by ashleahhill** [tonistiigi/audiosprite#64]
When using the install command for ffmpeg from the [readme](https://github.com/tonistiigi/audiosprite#dependencies)

```
brew install ffmpeg --with-theora --with-libogg --with-libvorbis
```
I received this warning from brew: 

```
Warning: ffmpeg: this formula has no --with-libogg option so it will be ignored!
```

Seems to work fine

**Comment by SargoDarya** [comment]
I think the installation has changed since this has been introduced first. Recommended from the official compilation guide would be

```brew install automake fdk-aac git lame libass libtool libvorbis libvpx \
opus sdl shtool texi2html theora wget x264 x265 xvid yasm```

I'll test this out and update the README accordingly.

**Comment by SargoDarya** [comment]
Apparently here's the brew formula, the libogg option doesn't seem to exist anymore.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/ffmpeg.rb
