### ISSUE TITLE
trying to convert mp3 files to JSON but having some problem. Please help 

### ISSUE THREAD

**Issue by awaisnova** [tonistiigi/audiosprite#68]
Please help me for this error 

![untitled](https://user-images.githubusercontent.com/34363467/33927773-53f82b32-e005-11e7-8635-522f14ee50e8.png)

**Comment by SargoDarya** [comment]
Seems like you haven't installed ffmpeg properly. I'm not exactly sure on how to do it on windows in the Unix Subsystem though.

**Comment by awaisnova** [comment]
Please help me for this issue...

![dsbzx3lqsjwfcn7yx4x1vg](https://user-images.githubusercontent.com/34363467/34029027-0dd1a76c-e188-11e7-9fe8-3bca40127979.png)

**Comment by awaisnova** [comment]
sir do you know about any other library to convert mp3 file to json and .dat file.? @SargoDarya SargoDarya

**Comment by SargoDarya** [comment]
Writing me an email without anything just providing the screenshot is definitely stepping over a line here. If you're not sure on how to deal with the command line and exports you might want to read up on that with google first. Seeing how this is not really an issue I'm going to close this.
